# Canvia aquest valor per escollir la BD: mysql o postgres
db.type=mysql

# MySQL
mysql.url=jdbc:mysql://localhost:3306/Pillam
mysql.user=root
mysql.password=pirineus

# PostgreSQL
postgres.url=jdbc:postgresql://localhost:5432/Pillam
postgres.user=postgres
postgres.password=pirineus